### ISSUE TITLE
GPIO / Switch inverted 

### ISSUE THREAD

**Issue by ghost** [trilliwon/homebridge-pio#1]
Hi,

Tried homebridge-gpio-wp2 out before and none of them worked. Getting a lot of bugs and crashes.

However just tried this new plugin out and it works great, thank you for that. But I have a small issue. I got a LED hooked up to a GPIO pin and it works very well. But when the light is off the toggle in ky home app is on, and when the light is on the toggle is off. Is there anyway to invert this behavior?

**Comment by trilliwon** [comment]
@ProjectAsphaleia 

HI, can you provide more detail?
Do you mean toggling is inverted? So you want to invert onoff?

**Comment by trilliwon** [comment]
@ProjectAsphaleia 

```
GPIOAccessory.prototype.setSwitch = function(on, callback) {
  this.log("Setting " + on);
	if (on) {
		relay.writeSync(0);
	} else {
		relay.writeSync(1);
  }
	callback();
}
```
This is the code for on and off
 If on is true, then write 0, else write 1. I thinks it is the problem.

**Comment by ghost** [comment]
Yes exactly. 
When my light is off, the toggle in the Home kit says its on.
I'll try changing the code with what you provided and will report back.

Edit: worked, thank you.
